name: mon premier workflows

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HelloWorld"
      - uses: actions/checkout@v4
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with gradle
        run: ./gradlew build
